### ISSUE TITLE
Lightmapped Specular Flashes In and Out of Existence

### ISSUE THREAD

**Issue by Enverex** [z3y/shaders#30] opened 2024-02-02 19:13 UTC
I was recently trying out this shader and it's mostly fine except one issue - the lightmapped specular seems to flash in and out of existence depending on the camera angle. This happens both in the editor and in-game.

I've recorded what it looks like here - https://youtu.be/Cc4j4TOqmXQ

Here's an example material that is experiencing this issue.
![image](https://github.com/z3y/shaders/assets/958670/27a93ff7-01e8-4bc4-96db-946decf90a54)

I've not had this issue with Silent's Filamented or Mochie Standard (which both have this ability).

**Comment by z3y** [comment] 2024-02-02 19:30
I havent seen anything like this before and I regularly use this shader. You would have to send an example scene, if you can isolate some parts, so i can reproduce this issue since I really dont know what it could be. Thanks

**Comment by Enverex** [comment] 2024-02-02 20:18
Creating a sample scene may be an issue but I'll see what I can do.

Another thing of note, turning off GPU Instancing seems to fix it, but obviously that's going to incur a performance hit so I'd rather not have to do that.

**Comment by z3y** [comment] 2024-02-05 15:44
Do you have UNITY_SPECCUBE_BLENDING disabled in the config? It might be related to something else

**Comment by z3y** [comment] 2024-02-06 17:22
this should be fixed now

**Closed as completed by z3y** 2024-02-06 17:22 UTC

**Comment by Enverex** [comment] 2024-02-06 20:44
Amazing, thanks. To answer your question, I don't remember ever seeing / changing anything to do with UNITY_SPECCUBE_BLENDING but that isn't to say something else in the project hasn't.
